services:
  frontend:
    build:
      context: ./bioconnect_client
      dockerfile: ./Dockerfile.dev
      args:
        - REACT_APP_BACKEND_URL=backend
        - NODE_ENV=development
        - REACT_APP_API_URL=https://random-data-api.com/api/v2/
        - REACT_APP_MAPBOX_TOKEN=pk.eyJ1Ijoiam9obnF3ZXJ0eSIsImEiOiJjbGFtYzIyc2kwZWlqM3JvYjNnZXkyczhjIn0.H6l2mPlL4J8zKYMhgtiCRg
    ports:
      - 3000:3000
    volumes:
      - ./bioconnect_client/src:/usr/src/app/src
  nginx:
    build:
      context: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
        - 80:80
        - 443:443 
    restart: always

  backend:
    build:
      context: ./BioConnect
      dockerfile: ./Dockerfile.dev
    ports:
      - '8080:8080'
    expose:
      - '8080'

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data:
  bioconnect_client:
