services:
  frontend:
    build:
      context: ./bioconnect_client
      args:
        - REACT_APP_BACKEND_URL=/backend
        - NODE_ENV=production
    ports:
      - 80:3000
  backend:
    build:
      context: ./BioConnect
    ports:
      - '8080:8080'
    expose:
      - '8080'

  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
